# Generated by Django 3.2.14 on 2022-07-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
                ('summary', models.TextField(db_column='summary')),
                ('deadline', models.TextField(db_column='deadline')),
                ('priority', models.CharField(db_column='priority', max_length=399)),
                ('status', models.CharField(db_column='status', max_length=399)),
                ('assignee', models.IntegerField(db_column='assignee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
