# Generated by Django 3.2.14 on 2022-07-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboard',
            table='tasks',
        ),
    ]
