# Generated by Django 3.2.14 on 2022-07-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_dashboard_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='assignee',
            field=models.IntegerField(db_column='assignee'),
        ),
    ]
